# Generated by Django 3.1.7 on 2021-04-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnewpercel',
            old_name='newpercel_name',
            new_name='newmerchant_name',
        ),
    ]
