# Generated by Django 3.1.7 on 2021-04-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210426_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='createorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_merchant', models.CharField(choices=[('1', 'stylezone'), ('2', 'delivery1'), ('3', 'merchant2'), ('4', 'merchant3'), ('5', 'merchant4')], max_length=300)),
                ('product_type', models.CharField(choices=[('1', 'stylezone'), ('2', 'delivery1'), ('3', 'merchant2'), ('4', 'merchant3'), ('5', 'merchant4')], max_length=300)),
                ('merchant_id', models.CharField(max_length=4)),
            ],
        ),
    ]
